# Generated by Django 5.0.6 on 2024-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('1', 'Ежедневно'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('weekly', 'Еженедельно')], default='daily', help_text='Укажите периодичность выполнения', max_length=50, verbose_name='Периодичность выполнения'),
        ),
    ]
